"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/sections/Footer";
import Header from "@/sections/Header";
import { usePathname } from "next/navigation";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

const metadata: Metadata = {
	title: "Eshop | Shopping Platform",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const pathname = usePathname();

	const noHeaderPaths = ["/sign-in", "/sign-up"];

	return (
		<html lang="en" data-theme="light">
			<head>
				<link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased px-2`}>
				{!noHeaderPaths.includes(pathname) && <Header />}
				{children}
				<Footer />
				<Toaster></Toaster>
			</body>
		</html>
	);
}
